### ISSUE TITLE
what does it do and how to install it win

### ISSUE THREAD

**Issue by ghost** [ifyour/deeplx-balance-server#1]
what does it do and how to install it win?

**Comment by ifyour** [comment]
Deploy multiple [DeepLx](https://github.com/OwO-Network/DeepLX) services, try DeepL for free, and use responsible balancing to handle requests and avoid errors from too frequent requests.

You can fork it and deploy it to [Vercel](https://vercel.com/).

**Comment by ghost** [comment]
@ifyour do i just have to deploy it on vercel or create multiple deeplx on vercel too? if so how can i deploy multiple deeplx? i can deploy one in my local pc?

**Comment by ifyour** [comment]
Yes, you can deploy locally or to some PasS platforms such as

- https://www.fl0.com
- https://zeabur.com

A single server with a high frequency of requests can cause 429 errors, which can be mitigated when you use load balancing.

**Comment by ghost** [comment]
@ifyour thank you, i should use deeplx's binary or docker? and balance server should be on vercel too right (beginner sorry)

**Comment by ghost** [comment]
@ifyour how did you deploy deeplx and balance server on vercel? i could did fl0 and zeabur i could not on vercel, can you write instructions for deeplx and balance server please?
also which format env should be url1, url2 or url1 , url2
